# Le decimos a Spring Boot que importe las variables de nuestro archivo .env local
spring.config.import=optional:file:.env[.properties]

# =======================================================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL)
# =======================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# =======================================================
# 'update': Actualiza el esquema de BD automáticamente según las entidades (Ideal para Desarrollo)
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola (ayuda a depurar)
spring.jpa.show-sql=true
# Formatea el SQL para que sea legible
spring.jpa.properties.hibernate.format_sql=true
# Dialecto específico para aprovechar características de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =======================================================
# CONFIGURACIÓN DE JWT
# =======================================================
# Nuestra clave secreta inyectada desde el .env
jwt.secret=${JWT_SECRET_KEY}
# Expiración del token en milisegundos (ej: 86400000 ms = 24 horas)
jwt.expiration=86400000
